export const SliderData = [
    {
      image:
        'https://i.imgur.com/N7uS0BA.jpg'
    },
    {
      image:
        'https://i.imgur.com/OUYSkUq.jpg'
    },
    {
      image:
        'https://i.imgur.com/NAPGPsI.jpg'
    },
    {
      image:
        'https://i.imgur.com/FAwOsw9.jpg'
    },
    {
      image:
        'https://i.imgur.com/WJVtdNK.jpg'
    },
    {
      image:
        'https://i.imgur.com/t8GgWMw.jpeg'
    },
    {
      image:
        'https://i.imgur.com/w3JDyjw.jpeg'
    },
    {
      image:
        'https://i.imgur.com/6RTaAcw.jpg'
    }

  ];